### ISSUE TITLE
提供的数据集解析错误

### ISSUE THREAD

**Issue by Always066** [Len-Li/openvino-robomaster#1]
Hi,很赞赏你们的工作！👍

但是我遇到一个小问题，在解析你们百度云盘提供的coco数据集时，我尝试可视化bbox的框到对应的图片上，但是总是无法得到正确的结果，请问云盘内的数据集是已经切割好的数据集吗？

**Comment by Len-Li** [comment]
是的，是切割好的图片


 
---原始邮件---
发件人: "Alway066"<notifications@github.com&gt;
发送时间: 2020年7月28日(星期二) 中午12:33
收件人: "Len-Li/openvino-robomaster"<openvino-robomaster@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Len-Li/openvino-robomaster] 提供的数据集解析错误 (#1)




 
Hi,很赞赏你们的工作！👍
 
但是我遇到一个小问题，在解析你们百度云盘提供的coco数据集时，我尝试可视化bbox的框到对应的图片上，但是总是无法得到正确的结果，请问云盘内的数据集是已经切割好的数据集吗？

**Comment by Always066** [comment]
json文件里面的annotation中的bbox的四个值对应边界框的中点xy和框的宽和高吗(bbox=[x,y,width,height])

**Comment by Len-Li** [comment]
四个数分别是左上角顶点x，y，width highth


 
---原始邮件---
发件人: "Alway066"<notifications@github.com&gt;
发送时间: 2020年7月28日(星期二) 中午1:45
收件人: "Len-Li/openvino-robomaster"<openvino-robomaster@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"lilelife"<1598185056@qq.com&gt;;
主题: Re: [Len-Li/openvino-robomaster] 提供的数据集解析错误 (#1)




 
json文件里面的annotation中的bbox的四个值对应边界框的中点xy和框的宽和高吗(bbox=[x,y,width,height])

**Comment by Always066** [comment]
抱歉，我还是没有弄懂，在train文件夹内部的00000004.jpg图片里面是没有红色和蓝色目标的，
{'segmentation': [178, 120, 206, 120, 206, 135, 178, 135], 'area': 420, 'iscrowd': 0, 'image_id': 4, 'bbox': [178, 120, 28, 15], 
'category_id': 1, 'id': 9, 'ignore': 0},这是id为4的annotation，里面说有一个目标，类别id为1应该是蓝色
"categories": [{"name": "armor_blue", "id": 1}, {"name": "armor_red", "id": 2}]}

**Comment by Len-Li** [comment]
有两个可能
1.官方提供的数据集标注错误
2.我在切割时遵循的是物体中央点落入图像则将其归类为该图片的标注，所以可能该物体被截断
不嫌麻烦的话加我微信13129470903


 
---原始邮件---
发件人: "Alway066"<notifications@github.com&gt;
发送时间: 2020年7月28日(星期二) 下午2:08
收件人: "Len-Li/openvino-robomaster"<openvino-robomaster@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"lilelife"<1598185056@qq.com&gt;;
主题: Re: [Len-Li/openvino-robomaster] 提供的数据集解析错误 (#1)




 
抱歉，我还是没有弄懂，在train文件夹内部的00000004.jpg图片里面是没有红色和蓝色目标的，
 {'segmentation': [178, 120, 206, 120, 206, 135, 178, 135], 'area': 420, 'iscrowd': 0, 'image_id': 4, 'bbox': [178, 120, 28, 15],
 'category_id': 1, 'id': 9, 'ignore': 0},这是id为4的annotation，里面说有一个目标，类别id为1应该是蓝色
 "categories": [{"name": "armor_blue", "id": 1}, {"name": "armor_red", "id": 2}]}
