### ISSUE TITLE
百度云链接挂掉了

### ISSUE THREAD

**Issue by sheng00125** [Len-Li/openvino-robomaster#2]
“下载链接：[百度云](https://pan.baidu.com/s/105vjTcDs6XZHtnXAgCx86g )
提取码：v8yg”
可以再分享一下嘛？感谢！

**Comment by Len-Li** [comment]
对不起呀，我在我的百度网盘里找了一会，没找到这份文件在哪，可能被我误删了。
这份数据可以用官方开源的数据集经过处理得到。官方的数据集在：https://bbs.robomaster.com/forum.php?mod=viewthread&tid=9678
