### ISSUE TITLE
大哥，帮助一下初中生

### ISSUE THREAD

**Issue by StanleyData** [Len-Li/openvino-robomaster#4]
您好伟大的len-li, 我是一个初中生，参加初中组的robomaster比赛。这个github非常的好，可惜我们初中组运用的机器人与大学组的机器人完全不同（看图片）
![屏幕截图(68)](https://user-images.githubusercontent.com/79580759/214047171-b4d078a2-7328-4152-b2e1-8ee1e6836ab4.png)
您能不能帮我们也做一个如此简单的模型训练教程？谢谢

**Comment by Len-Li** [comment]
同学你好，

很羡慕你们作为初中生就能接触到robomaster了，我初中时还在玩泥巴呢。

我已经不做robomaster很久了，所以对初中组的情况也不了解，但我猜大疆官方已经提供了视觉模型的教程，毕竟还是初中，从0开始训一个神经网络还是有难度的。

我简单在大疆的文档搜索了一下，https://www.dji.com/cn/robomaster-s1/programming-guide
这个文档里的“智能”部分里有讲解如何调用视觉接口，你看看能不能满足你们的需求。

祝比赛顺利
